api:
   build: ./api
   ports: 
      - 3000:3000
   volumes:
      - ./api:/go/src/github.com/VictorEspiritu/project/api
   links:
      - database
   environment:
      - DB_NAME=project

database:
   image: mongo:3.0
   command: mongod --smallfiles --quite --logpath=/dev/null



